{
  "parameters": {
    "issueName": "default",
    "api-version": "2021-01-01"
  },
  "responses": {
    "200": {
      "body": {
        "id": 10000064644594,
        "title": "Potential control plane issue detected in [eastus] involving at least 2 incident(s)",
        "summary": "",
        "confidence": 0.70724761582106965,
        "displayConfidence": "Medium",
        "plane": "Control Plane",
        "location": "eastus",
        "correlatedIncidentCount": 2,
        "firstReportTime": "2020-10-23T17:57:01.6849525+00:00",
        "lastReportTime": "2020-10-23T19:07:10.2354825+00:00",
        "rawIds": [
          123,
          456
        ],
        "duplicateIds": [
          123456,
          23423
        ],
        "outageDeclared": true,
        "expired": false,
        "incidents": [
          {
            "id": 210687646,
            "severity": 3,
            "state": "ACTIVE",
            "createdDate": "2020-10-23T17:46:35.02+00:00",
            "sourceCreateTime": "0001-01-01T00:00:00+00:00",
            "lastModifiedDate": "0001-01-01T00:00:00+00:00",
            "title": "ApiUnexpectedFailures exceeded thresholds for  ApiName: availabilitysets.starttenantupdate.post. Location: eastus. ResultCode: networkinginternaloperationerror. ApiUnexpectedFailuresCount = 379 over last 30 minutes ApiUnexpectedFailuresRatio = 0.06184725848563968 over last 30 minutes ApiUnexpectedFailuresFailedSubIdCount = 10 over last 30 minutes",
            "summary": "This is a sample summary",
            "description": "This is a sample description",
            "cloudInstanceId": 0,
            "responsibleServiceId": 123456,
            "responsibleTeamId": 123456,
            "owningServiceId": 10045,
            "serviceCategoryId": 1,
            "owningTeamId": 10661,
            "originatingServiceId": 123456,
            "isCustomerImpacting": false,
            "isNoise": false,
            "isSecurityRisk": false,
            "keywords": "test",
            "type": "outage",
            "parentId": "123456",
            "impactedServices": [],
            "impactedTeams": [],
            "incidentManagerContactId": 123456,
            "communicationsManagerContactId": 123456,
            "siteReliabilityContactId": 123456,
            "diagnosticsLink": "samplelink",
            "isOutage": true,
            "occuringLocation": {
              "environment": "test",
              "datacenter": "east us",
              "role": "sample role",
              "instance": "sample instance",
              "component": "sample component",
              "slice": "sample slice"
            },
            "bridges": [],
            "owningTenantName": "Cloudnet",
            "owningTeamName": "owningTeamName",
            "contactAlias": "knuj",
            "createdBy": "knuj",
            "impactStartTime": "2020-10-23T10:57:01.6849525+00:00",
            "acknowledgeBy": "knuj",
            "incidentManagerAlias": "knuj",
            "acknowledgeTime": "2020-10-23T11:57:01.6849525+00:00",
            "mitigateData": {
              "mitigatedBy": "knuj",
              "mitigateTime": "2020-10-23T13:57:01.6849525+00:00"
            },
            "resolveData": {
              "resolvedBy": "knuj",
              "resolveTime": "2020-10-23T13:57:01.6849525+00:00"
            }
          }
        ]
      }
    }
  }
}
